name: pokemon
description: A Pokedex application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Bloc state management
  flutter_bloc: ^8.0.1
  # Service Locator
  get_it: ^7.2.0
  # dart Basic Utils
  basic_utils: ^4.2.0
  # Logs printer
  logger: ^1.1.0
  # Storage for simple data
  shared_preferences: ^2.0.13
  rxdart: ^0.27.3
  # retrofit dio wrapper dependency
  retrofit: ^3.0.1+1
  # Pretty logger json interceptor
  pretty_dio_logger: ^1.1.1
  # NoSQL database
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  # JSON
  json_annotation: ^4.4.0
  # autocomplete widget
  flutter_typeahead: ^3.2.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  # JSON convert
  json_serializable: ^6.1.5
  # NoSQL database
  hive_generator: ^1.1.2
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/poke_ball_icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  assets:
    # image files
    - assets/images/